export interface LandmarkDefinition {
    id: number;
    name: string;
    image: any; 
    description?: string;
}

export const FRONT_LANDMARKS: LandmarkDefinition[] = [
    { id: 1, name: 'Hairline', image: require('../../resources/front/1hairline.webp') },
    { id: 2, name: 'Left Eye Pupil', image: require('../../resources/front/2leftEyePupil.webp') },
    { id: 3, name: 'Right Eye Pupil', image: require('../../resources/front/3rightEyePupil.webp') },
    { id: 4, name: 'Nose Left', image: require('../../resources/front/4noseLeft.webp') },
    { id: 5, name: 'Nose Right', image: require('../../resources/front/5noseRight.webp') },
    { id: 6, name: 'Lower Lip', image: require('../../resources/front/6lowerLip.webp') },
    { id: 7, name: 'Chin Bottom', image: require('../../resources/front/7chinBottom.webp') },
    { id: 8, name: 'Left Outer Ear', image: require('../../resources/front/8leftOuterEar.webp') },
    { id: 9, name: 'Right Outer Ear', image: require('../../resources/front/9rightOuterEar.webp') },
    { id: 10, name: 'Left Temple', image: require('../../resources/front/10leftTemple.webp') },
    { id: 11, name: 'Right Temple', image: require('../../resources/front/11rightTemple.webp') },
    { id: 12, name: 'Left Eye Medial Canthus', image: require('../../resources/front/12leftEyeMedialCanthus.webp') },
    { id: 13, name: 'Left Eye Lateral Canthus', image: require('../../resources/front/13leftEyeLateralCanthus.webp') },
    { id: 14, name: 'Left Eye Upper Eyelid', image: require('../../resources/front/14leftEyeUpperEyelid.webp') },
    { id: 15, name: 'Left Eye Lower Eyelid', image: require('../../resources/front/15leftEyeLowerEyelid.webp') },
    { id: 16, name: 'Left Eyelid Hood End', image: require('../../resources/front/16leftEyelidHoodEnd.webp') },
    { id: 17, name: 'Left Brow Head', image: require('../../resources/front/17leftBrowHead.webp') },
    { id: 18, name: 'Left Brow Inner Corner', image: require('../../resources/front/18leftBrowInnerCorner.webp') },
    { id: 19, name: 'Left Brow Arch', image: require('../../resources/front/19leftBrowArch.webp') },
    { id: 20, name: 'Left Brow Peak', image: require('../../resources/front/20leftBrowPeak.webp') },
    { id: 21, name: 'Left Brow Tail', image: require('../../resources/front/21leftBrowTail.webp') },
    { id: 22, name: 'Left Upper Eyelid Crease', image: require('../../resources/front/22leftUpperEyelidCrease.webp') },
    { id: 23, name: 'Right Eye Medial Canthus', image: require('../../resources/front/23rightEyeMedialCanthus.webp') },
    { id: 24, name: 'Right Eye Lateral Canthus', image: require('../../resources/front/24rightEyeLateralCanthus.webp') },
    { id: 25, name: 'Right Eye Upper Eyelid', image: require('../../resources/front/rightEyeUpperEyelid.webp') }, 
    { id: 26, name: 'Right Eye Lower Eyelid', image: require('../../resources/front/26rightEyeLowerEyelid.webp') },
    { id: 27, name: 'Right Eyelid Hood End', image: require('../../resources/front/27rightEyelidHoodEnd.webp') },
    { id: 28, name: 'Right Brow Head', image: require('../../resources/front/28rightBrowHead.webp') },
    { id: 29, name: 'Right Brow Inner Corner', image: require('../../resources/front/29rightBrowInnerCorner.webp') },
    { id: 30, name: 'Right Brow Arch', image: require('../../resources/front/30rightBrowArch.webp') },
    { id: 31, name: 'Right Brow Peak', image: require('../../resources/front/31rightBrowPeak.webp') },
    { id: 32, name: 'Right Brow Tail', image: require('../../resources/front/32rightBrowTail.webp') },
    { id: 33, name: 'Right Upper Eyelid Crease', image: require('../../resources/front/33rightUpperEyelidCrease.webp') },
    { id: 34, name: 'Nasal Base', image: require('../../resources/front/34nasalBase.webp') },
    { id: 35, name: 'Nose Bottom', image: require('../../resources/front/35noseBottom.webp') },
    { id: 36, name: 'Left Nose Bridge', image: require('../../resources/front/36leftNoseBridge.webp') },
    { id: 37, name: 'Right Nose Bridge', image: require('../../resources/front/37rightNoseBridge.webp') },
    { id: 38, name: 'Mouth Left', image: require('../../resources/front/38mouthLeft.webp') },
    { id: 39, name: 'Mouth Right', image: require('../../resources/front/39mouthRight.webp') },
    { id: 40, name: 'Cupids Bow', image: require('../../resources/front/40cupidsBow.webp') },
    { id: 41, name: 'Inner Cupids Bow', image: require('../../resources/front/41innerCupidsBow.webp') },
    { id: 42, name: 'Mouth Middle', image: require('../../resources/front/42mouthMiddle.webp') },
    { id: 43, name: 'Left Top Gonion', image: require('../../resources/front/43leftTopGonion.webp') },
    { id: 44, name: 'Right Top Gonion', image: require('../../resources/front/44rightTopGonion.webp') },
    { id: 45, name: 'Left Bottom Gonion', image: require('../../resources/front/45leftBottomGonion.webp') },
    { id: 46, name: 'Right Bottom Gonion', image: require('../../resources/front/46rightBottomGonion.webp') },
    { id: 47, name: 'Chin Left', image: require('../../resources/front/47chinLeft.webp') },
    { id: 48, name: 'Chin Right', image: require('../../resources/front/48chinRight.webp') },
    { id: 49, name: 'Neck Left', image: require('../../resources/front/49neckLeft.webp') },
    { id: 50, name: 'Neck Right', image: require('../../resources/front/50neckRight.webp') },
    { id: 51, name: 'Left Cheek', image: require('../../resources/front/51leftCheek.webp') },
    { id: 52, name: 'Right Cheek', image: require('../../resources/front/52rightCheek.webp') },
];
